{% set version = "4.6-3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-doby
  version: {{ version|replace("-", "_") }}

source:
  fn: doBy_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/doBy_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/doBy/doBy_{{ version }}.tar.gz
  sha256: 6518cf6588df0d87803925152b928725b224d44e55024d6589e485a8f8350db4

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-mass
    - r-matrix
    - r-dplyr
    - r-magrittr
    - r-plyr
  run:
    - r-base
    - r-mass
    - r-matrix
    - r-dplyr
    - r-magrittr
    - r-plyr

test:
  commands:
    - $R -e "library('doBy')"           # [not win]
    - "\"%R%\" -e \"library('doBy')\""  # [win]

about:
  home: http://people.math.aau.dk/~sorenh/software/doBy/
  license: GPL (>= 2)
  summary: 'Contains: 1) Facilities for working with grouped data: ''do'' something to data stratified
    ''by'' some variables. 2) LSmeans (least-squares means), general linear contrasts.  3)
    Miscellaneous other utilities.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
