{% set version = "4.6-2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-doby
  version: {{ version|replace("-", "_") }}

source:
  fn: doBy_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/doBy_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/doBy/doBy_{{ version }}.tar.gz
  sha256: ab9644ab891d5d26689228dbb4fccce397aeacab93aa1835358ffbe76cda6b0b

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-mass
    - r-matrix
  run:
    - r-base
    - r-mass
    - r-matrix

test:
  commands:
    - $R -e "library('doBy')"  # [not win]
    - "\"%R%\" -e \"library('doBy')\""  # [win]

about:
  home: http://people.math.aau.dk/~sorenh/software/doBy/
  license: GPL (>= 2)
  summary: 'The facilities can roughly be grouped as:  . 1) Facilities for groupwise computations
    of summary statistics and other facilities for working with grouped data: ''do''
    something to data  stratified ''by'' some variables.   . 2) LSmeans (least-squares
    means), general linear contrasts. . 3) Miscellaneous other utilities.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
