appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: rwJZBirSgHPsptayE9mrV/e5qhcsVFuFRmppuca0uxtA3KeInQOWjIFd6is40sU2JW70UPclRcEJUSjU6zMIUTy/2q0C1yMz4FKw+CNwqPkHqq3NGeU+4X99vRGpHOsKRZW/Gq28R0z17Ty1Erkf6Qj2kcrZ1IPp0YDd5f6/ukxdfYAlGOknBfKdOczteB5tCSs8fepnelXn8eXvK9WKg3wTNB61i8gPP2nE0W9tyHXiOYwoNF8mw8Kbeuxjgo9yCb7qiNPyp99FcRJpK092cp0odeYVG50tVGL7tV73eF3CNSM50owHirVOdHbjLpW8rEZKvuNoR3irQdzkTey4yv7Bg9WER7aAgczZN+SRPiAf/FOn6UfC44ToRaRUHQD5pAkLzjM87tJfRog47qrGv5gzVIs1cXAC3vusJe358zmZS0xKmq5Wvs+XO/xwOzMC9prc5LwT9SQdnCkf7z0GD20PeAjqG/MztyxUGEL1h1u24/jIa1IGlkV6g2GPuYAU5ZHsDk9ULRKQYIDfxvrsKhq8JLUkP95yrnCgM96UQKPHNPig6WRnI3Bd4HRvJnVfR1zvqppu1E2XXdPbdXBckuB/PM+FLJurhTHRnH9vgX/z/bgybslnwS+mITENbgd+uBDf7cFpjEkcBSeTeBBlfVXYEQ5DPNNw/hXodYBuh3I=}
bot:
  automerge: true
