travis:
  secure:
    BINSTAR_TOKEN: tzYBiXAw79zeG8BAGpObW4xehnMvh7uDhvPpgdN3plZGv2SUa2Yt5tZitCrlz8AByOedihxPcvHwSkD1rq5YB5kJJk5aomzhADlBKn8F4o/c7PQcBcmunvJ/0x4Qu/HFgNdh4XUnTXBysA0NWIb7laY+sv0Lethzf+LTdgRtjdNQw2HkbyGwxOP7gZM3OjPmYEdy075DhETvGv8kQtgsWtY9NdwvgOWPtUwAj5YR10DpdHgYfbaxZQlKfQc8T3/SsJrSZOGQjp73ZC3sUIfZQF28QMPQ89lsY8OEpD1LW7DuE9XfwaCtyRe+3PwudEFf7seP8Xwt6Cbvz8oenTb92g38FIFda+edtNewgA6Y+dnjSSdBaqWmWZiqJL2canoT8//2xjIVPHaYGzbn7ZCCfAG9b9KXsNCYoAr5rY78/8rt2nB9TB7PgaM5qWvJNdHG5AnjGWTyejcoXVfAxoGD6QKQhxbzdCmbryaTkjywYpiGWoX5inCOnyP/vMz4ZUYGva/YwJIBJc8OXD1zaoBkWGkxRwBIxeuhBmP0g5yiW3TptOYSm/fDYB3JY1NchdHNtFnz0QMgp/OtiHMld4w7w20MHZzOKGq0/WGO0LHbm1A9GqG8eRaRfojJvOyi03mXeaK2c4vBpyrFKwp/eN8aY8HtLbuQcntR63SRIW57dAo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
